name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Убедитесь, что используете корректную версию Node.js

      - name: Remove package-lock and node_modules
        run: |
          rm -f package-lock.json
          rm -rf node_modules

      - name: Install dependencies
        run: npm install

      - name: Package the app
        run: npm run make

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v1
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

