name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Remove package-lock and node_modules
        run: |
          rm -f package-lock.json
          rm -rf node_modules

      - name: Install dependencies
        run: npm install

      - name: Package the app
        run: npm run make

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3  # Обновлено на v3
        with:
          name: build-output
          path: out/

#      - name: Install Firebase CLI
#        run: npm install -g firebase-tools@latest

#      - name: Deploy to Firebase Hosting
#        uses: FirebaseExtended/action-hosting-deploy@v0
#        with:
#          repoToken: ${{ secrets.GITHUB_TOKEN }}
#          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
#          channelId: live
#          projectId: electronenglishwords